version: "3.9"
services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
