services:
  backend:
    build: ./todo-app/backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./todo-app/frontend
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
